import AboutUs from '@/components/marketing/about'
import { Metadata } from 'next';
export const metadata: Metadata = {
  title: "About Us || Arkin Organics",
  description: "Generated by Hytek",
};

export default function page() {
  return (
    <AboutUs/>
  )
}
