import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster as ReactHotToast} from 'react-hot-toast';
import { Toaster } from "@/components/ui/sonner"
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Arkin Organics",
  description: "Generated by Hytek",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
    
        {children}
        {/* <ReactHotToast
          toastOptions={{
            className: "",
            duration: 3000,
            style: {
              background: "#333",
              color: "#fff",
            
            },
            position: "top-center",
          }}
          /> */}
       <Toaster position="top-right" richColors />
      </body>
    </html>
  );
}
